package project;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import com.itextpdf.text.BadElementException;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.Font.FontFamily;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.*;
/**
 *
 * @author NODE5
 */
public class bcinformationpage extends JFrame {
        String no1;
        Date dt1=new Date("10/02/2003");
        String name1;
        String year1;
        String semester1;
        String course1;
        String reason1,enrollmentno,file;
        int successful,i;
    public bcinformationpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        reason = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        back = new javax.swing.JButton();
        no = new javax.swing.JLabel();
        Nofill = new javax.swing.JTextField();
        date = new javax.swing.JLabel();
        datefill = new com.toedter.calendar.JDateChooser();
        year = new javax.swing.JLabel();
        enrolment1 = new javax.swing.JLabel();
        enrollmentnofill = new javax.swing.JTextField();
        yearfill1 = new com.toedter.calendar.JYearChooser();
        yearfill2 = new com.toedter.calendar.JYearChooser();
        filltcnobuttion = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        reasonfill = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bonafied Certificate");
        setFocusCycleRoot(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 0), 4, true));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1355, 695));

        reason.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        reason.setText("Reason");

        submit.setBackground(new java.awt.Color(204, 204, 204));
        submit.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(204, 204, 204));
        back.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        no.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        no.setText("No.");
        no.setPreferredSize(new java.awt.Dimension(27, 18));

        Nofill.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        Nofill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NofillActionPerformed(evt);
            }
        });

        date.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        date.setText("Date");

        datefill.setBackground(new java.awt.Color(255, 255, 102));
        datefill.setDateFormatString("dd/MM/yyyy");
        datefill.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N

        year.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        year.setText("Year");

        enrolment1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        enrolment1.setText("Enrollment No.");

        enrollmentnofill.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        enrollmentnofill.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                enrollmentnofillKeyTyped(evt);
            }
        });

        yearfill1.setBackground(new java.awt.Color(255, 255, 102));
        yearfill1.setValue(2018);

        yearfill2.setBackground(new java.awt.Color(255, 255, 102));

        filltcnobuttion.setBackground(new java.awt.Color(255, 255, 102));
        filltcnobuttion.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        filltcnobuttion.setText("Number Fill");
        filltcnobuttion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filltcnobuttionActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel8.setText("Student Information Management System");

        reasonfill.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        reasonfill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reasonfillActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 153, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Bonafied Certificate");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(416, 416, 416)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reason)
                            .addComponent(enrolment1)
                            .addComponent(no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date)
                            .addComponent(year))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(back)
                        .addGap(63, 63, 63)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reasonfill, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datefill, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Nofill, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filltcnobuttion))
                    .addComponent(enrollmentnofill, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(submit)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(yearfill1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(yearfill2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(373, 373, 373))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(546, 546, 546)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(326, 326, 326))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel8)
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enrolment1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enrollmentnofill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reason, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reasonfill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(no, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Nofill)
                        .addComponent(filltcnobuttion)))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearfill1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearfill2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(back)
                            .addComponent(submit)))
                    .addComponent(datefill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        dispose();
        new firstpage().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void NofillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NofillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NofillActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        reason1=reasonfill.getText();
        String abc1234=Integer.toString(yearfill1.getYear());
        String abc1235=Integer.toString(yearfill2.getYear());
        if(reason1.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Please enter Reason");
            }
        else
        {
        try
        {
            no1=Nofill.getText();
            enrollmentno=enrollmentnofill.getText();
            //reason1=reason.getText();
            dt1=datefill.getDate();
            //Integer.parseInt(enrollmentnofill.getText());
            abc1234=abc1234.concat("-");
            abc1234=abc1234.concat(abc1235);
            year1=abc1234;
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            Connection con=DriverManager.getConnection("jdbc:ucanaccess://D:\\project\\project\\project.accdb");
            int i=0;
            String sql="SELECT Enrollment,Name,Course,coursesemester FROM registerpage";
            PreparedStatement p=con.prepareStatement(sql);
            ResultSet r=null;
            r=p.executeQuery();
        while (r.next())
        {
            if(r.getInt(1)==Integer.parseInt(enrollmentnofill.getText()))
            {
                i=1;
                name1=r.getString(2);
                course1=r.getString(3);
                String part=r.getString(4);
                String[] dividepart=part.split("-");
                String part1=dividepart[0];
                String part2=dividepart[1];
                char numbercourse=part2.charAt(0);
                    char schemecourse=part2.charAt(1);
                    if(numbercourse=='1')
                    {
                        semester1="1st";
                    }
                    if(numbercourse=='2')
                    {
                        semester1="2nd";
                    }
                    if(numbercourse=='3')
                    {
                        semester1="3rd";
                    }
                    if(numbercourse=='4')
                    {
                        semester1="4th";
                    }
                    if(numbercourse=='5')
                    {
                        semester1="5th";
                    }
                    if(numbercourse=='6')
                    {
                        semester1="6th";
                    }
                //semester1=
            }
            else
            {
                continue;
            }
        }
        if (i==1)
        {
            int number2=(Integer.parseInt(no1))+1;
                String sqltc="update documentno set bcnumber='"+number2+"' where id = 1";
                PreparedStatement p1tc=con.prepareStatement(sqltc);
                //p1tc.setInt(number2, 1);
                p1tc.executeUpdate();
         successful=document();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "number is not found");
        }
        }
        catch(ClassNotFoundException | SQLException | IOException | DocumentException | HeadlessException e )
        {
            JOptionPane.showMessageDialog(null, e);
        }
        catch(NumberFormatException nfe)
        {
            JOptionPane.showMessageDialog(null, " Please Enter All Information");    
        }
        catch(NullPointerException npe)
        {
         JOptionPane.showMessageDialog(null, " Please Enter Date");   
        }
        }
    }//GEN-LAST:event_submitActionPerformed

    private void enrollmentnofillKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enrollmentnofillKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)|| (c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE)))
        {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_enrollmentnofillKeyTyped

    private void filltcnobuttionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filltcnobuttionActionPerformed
        try
        {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            Connection con=DriverManager.getConnection("jdbc:ucanaccess://D:\\project\\project\\project.accdb");
            String sql1fill="SELECT [bcnumber] FROM documentno";

            PreparedStatement pfill;
            pfill = con.prepareStatement(sql1fill);

            ResultSet rfill=null;
            rfill=pfill.executeQuery();

            while(rfill.next())
            {
                Nofill.setText(rfill.getString(1));
            }

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_filltcnobuttionActionPerformed

    private void reasonfillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reasonfillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reasonfillActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bcinformationpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bcinformationpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bcinformationpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bcinformationpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bcinformationpage().setVisible(true);
                
               
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nofill;
    private javax.swing.JButton back;
    private javax.swing.JLabel date;
    private com.toedter.calendar.JDateChooser datefill;
    private javax.swing.JTextField enrollmentnofill;
    private javax.swing.JLabel enrolment1;
    private javax.swing.JButton filltcnobuttion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel no;
    private javax.swing.JLabel reason;
    private javax.swing.JTextField reasonfill;
    private javax.swing.JButton submit;
    private javax.swing.JLabel year;
    private com.toedter.calendar.JYearChooser yearfill1;
    private com.toedter.calendar.JYearChooser yearfill2;
    // End of variables declaration//GEN-END:variables
int document() throws BadElementException, IOException, DocumentException
{
    
    Document document = new Document();
        String file="D:\\project\\project\\bcdocument.pdf";
        File file1 = new File(file);
        String no=no1;
        
        String name=name1;
        SimpleDateFormat format1=new SimpleDateFormat("dd/MM/yyyy");     
        String dt=format1.format(dt1);
        String year=year1;
        String semester=semester1;
        String branch=course1;
        String r=reason1;
        document.setPageSize(PageSize.A4);
        Font f= new Font();
        f.setSize(24);
        //f.setFamily("TIMES NEW ROMAN");
        f.setFamily(FontFactory.TIMES_ROMAN);
        //f.setStyle("Times New Roman");
        Font f1= new Font();
        f1.setSize(18);
        //f1.setStyle("Times New Roman");
        f1.setFamily(FontFactory.TIMES_ROMAN);
        Font f2= new Font();
        f2.setStyle(Font.BOLD);
        ///f2.setStyle("Times New Roman");
        f2.setFamily(FontFactory.TIMES_ROMAN);
        Font f3=new Font();
        f3.setStyle(Font.BOLD);
        f3.setSize(18);
        f3.setFamily(FontFactory.TIMES_ROMAN);
        Font f4= new Font();
        f4.setSize(18);
        f4.setStyle(Font.BOLD);
        f4.setFamily(FontFactory.TIMES_ROMAN);
         try 
         {
                
                PdfWriter.getInstance(document,new FileOutputStream(file));
                document.open();
                Image image=Image.getInstance("D:\\project\\project\\collegelobo.png");
                Paragraph paragraphs =new Paragraph();
                paragraphs.setFont(f);
                paragraphs.setAlignment(3);
                image.setAlignment(1);
                paragraphs.add(image);
                paragraphs.add("GOVERNMENT POLYTECHINIC MURTIZAPUR\n\n");
                paragraphs.add("        NH6,MURTIZAPUR-AMRAVATI ROAD,\n\n                   HENDAJ, MURTIZAPUR\n\n");
                paragraphs.add("           DIST.AKOLA (MAHARASHTRA)\n\n");
                paragraphs.add("=====================================");
                paragraphs.setFont(f1);
                paragraphs.add("\n\n                                                                    No  :- ");
                paragraphs.setFont(f4);
                paragraphs.add(no);
                paragraphs.setFont(f1);
                paragraphs.add("\n\n                                                                    Dt. :- ");
                paragraphs.setFont(f1);
                paragraphs.add(dt+"\n");
                paragraphs.setFont(f1);
                paragraphs.setFont(f);
                paragraphs.add("\n\n                                 CERTIFICATE\n\n");
                paragraphs.setFont(f1);
                paragraphs.add("\n             This is to certify that ");
                paragraphs.setFont(f4);
                paragraphs.add(name);
                paragraphs.setFont(f1);
                paragraphs.add(" is a bonafied student of this institute during the year ");
                paragraphs.setFont(f4);
                paragraphs.add(year);
                paragraphs.setFont(f1);
                paragraphs.add(" studying in ");
                paragraphs.setFont(f4);
                paragraphs.add(semester);
                paragraphs.setFont(f1);
                paragraphs.add(" Semester of Diploma Course in ");
                paragraphs.setFont(f4);
                paragraphs.add(branch);
                paragraphs.setFont(f1);
                paragraphs.add("\n\n For ");
                paragraphs.setFont(f4);
                paragraphs.add(r);
                paragraphs.setFont(f1);
                paragraphs.add("\n\n\n\n\n\n\n\n                                                                      PRINCIPAL");
                paragraphs.add("\n                                                   GOVERNMENT POLYTECHINIC");
                paragraphs.add("\n                                                                     MURTIZAPUR");
                document.add(paragraphs);
                document.close();
                dispose();
                new firstpage().setVisible(true);
                Desktop.getDesktop().open(file1);
         }
         catch (FileNotFoundException ex) {
            System.out.println(ex);
        }
    return successful;
}
}
