package project;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.*;
/**
 *
 * @author NODE5
 */
public class btcardpage extends JFrame {
String no;
int enrollment1;
String coursecode1;
String ticketno1;
String name1;
    /**
     * Creates new form deletepage
     */
    public btcardpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        enrollmentno = new javax.swing.JLabel();
        enrollmentnofill = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        back5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ticketnumberfill = new javax.swing.JTextField();
        filltcnobuttion = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Borrow Ticket");

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 0), 4, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(1355, 695));

        enrollmentno.setBackground(new java.awt.Color(255, 204, 0));
        enrollmentno.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        enrollmentno.setText("Enrollment No");

        enrollmentnofill.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        enrollmentnofill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollmentnofillActionPerformed(evt);
            }
        });
        enrollmentnofill.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                enrollmentnofillKeyTyped(evt);
            }
        });

        submit.setBackground(new java.awt.Color(204, 204, 204));
        submit.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        back5.setBackground(new java.awt.Color(204, 204, 204));
        back5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        back5.setText("Back");
        back5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back5ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Ticket Number");

        ticketnumberfill.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N

        filltcnobuttion.setBackground(new java.awt.Color(255, 255, 102));
        filltcnobuttion.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        filltcnobuttion.setText("Number Fill");
        filltcnobuttion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filltcnobuttionActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel8.setText("Student Information Management System");

        jLabel2.setBackground(new java.awt.Color(255, 153, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Borrow Ticket");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 366, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(344, 344, 344))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(521, 521, 521)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(enrollmentno))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ticketnumberfill, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filltcnobuttion))
                            .addComponent(enrollmentnofill, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addComponent(back5)
                        .addGap(151, 151, 151)
                        .addComponent(submit)))
                .addContainerGap(493, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel8)
                .addGap(8, 8, 8)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enrollmentnofill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enrollmentno, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ticketnumberfill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filltcnobuttion))
                .addGap(111, 111, 111)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back5)
                    .addComponent(submit))
                .addGap(208, 208, 208))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back5ActionPerformed
dispose();
        new firstpage().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_back5ActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
try
        {
            no=ticketnumberfill.getText();
            enrollment1=Integer.parseInt(enrollmentnofill.getText());
            ticketno1=ticketnumberfill.getText();
            //reason1=reason.getText();
            //dt1=datefill.getDate();
            //year1=yearfill.getText();
            //semester1=semesterfill.getText();
            //reason1=reasonfill.getText();
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            Connection con=DriverManager.getConnection("jdbc:ucanaccess://D:\\project\\project\\project.accdb");
            int i=0;
            String sql="SELECT Enrollment,Name,coursesemester FROM registerpage";
            PreparedStatement p=con.prepareStatement(sql);
            ResultSet r=null;
            r=p.executeQuery();
        while (r.next())
        {
            if(r.getInt(1)==Integer.parseInt(enrollmentnofill.getText()))
            {
                i=1;
                name1=r.getString(2);
                coursecode1=r.getString(3);
            }
            else
            {
                continue;
            }
        }
        if (i==1)
        {
            int number2=(Integer.parseInt(no))+1;
            //JOptionPane.showMessageDialog(null, number2);
                String sqltc="update documentno set btnumber='"+number2+"' where id = 1";
                PreparedStatement p1tc=con.prepareStatement(sqltc);
                p1tc.executeUpdate();
         document();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "number is not found");
        }
        }
        catch(NumberFormatException eb)
        {
            JOptionPane.showMessageDialog(null, "Enter All Information");
        }
        catch(ClassNotFoundException em)
        {
            JOptionPane.showMessageDialog(null, em);
        }
       catch(SQLException ek)
       {
           JOptionPane.showMessageDialog(null, ek);
       }
       catch(HeadlessException eee)
       {
           JOptionPane.showMessageDialog(null, eee);
       }
       catch(NullPointerException npe)
       {
           JOptionPane.showMessageDialog(null, "Enter All Information");
       }
    }//GEN-LAST:event_submitActionPerformed

    private void enrollmentnofillKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enrollmentnofillKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)|| (c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE)))
        {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_enrollmentnofillKeyTyped

    private void filltcnobuttionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filltcnobuttionActionPerformed
        try
        {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            Connection con=DriverManager.getConnection("jdbc:ucanaccess://D:\\project\\project\\project.accdb");
            String sql1fill="SELECT [btnumber] FROM documentno";

            PreparedStatement pfill;
            pfill = con.prepareStatement(sql1fill);

            ResultSet rfill=null;
            rfill=pfill.executeQuery();

            while(rfill.next())
            {
                ticketnumberfill.setText(rfill.getString(1));
            }

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_filltcnobuttionActionPerformed

    private void enrollmentnofillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollmentnofillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enrollmentnofillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(btcardpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(btcardpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(btcardpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(btcardpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new btcardpage().setVisible(true);
               
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back5;
    private javax.swing.JLabel enrollmentno;
    private javax.swing.JTextField enrollmentnofill;
    private javax.swing.JButton filltcnobuttion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton submit;
    private javax.swing.JTextField ticketnumberfill;
    // End of variables declaration//GEN-END:variables

    private void document() {
        String file="D:\\project\\project\\btdocument.pdf";
        File file1 = new File(file);
        //int ticketno;
        //ticketno=8;
        //String name="Umesh D. Dange";
       // String coursecode="CO_5G";
        Font f=new Font();
        f.setStyle(Font.BOLD);
        f.setSize(16);
        f.setFamily(FontFactory.TIMES_ROMAN);
        //f.setStyle("Times New Roman");
        Font f1=new Font();
        f1.setFamily(FontFactory.TIMES_ROMAN);
        //f1.setStyle("Times New Roman");
        Font f2=new Font();
        f2.setStyle(Font.BOLD);
        f2.setFamily(FontFactory.TIMES_ROMAN);
        Font f3=new Font();
        f3.setFamily(FontFactory.TIMES_ROMAN);
        Document document = new Document();
        Rectangle r=new Rectangle(250,280);
        document.setPageSize(r);
        try
        {
                PdfWriter.getInstance(document,new FileOutputStream(file));
                document.open();
                Paragraph paragraph =new Paragraph();
                paragraph.setAlignment(0);
                paragraph.setFont(f);
                paragraph.add("Govt. Poly. Murtizapur");
                paragraph.setFont(f1);
                paragraph.add("\nTicket No.  :-  ");
                paragraph.setFont(f2);
                paragraph.add(ticketno1);
                paragraph.setFont(f1);
                paragraph.add("\nName:-");
                paragraph.setFont(f2);
                paragraph.add(name1);
                paragraph.setFont(f1);
                paragraph.add("\nSemester  :-  ");
                paragraph.setFont(f2);
                paragraph.add(coursecode1);
                paragraph.setFont(f1);
                paragraph.add("\n\nSpeciman Sigature      Librarian");
                PdfPTable t=new PdfPTable(1);
                PdfPCell c=new PdfPCell(new Paragraph("\n\n\n\n\n\n"));
                t.addCell(c);
                t.setWidthPercentage(40);
                t.setHorizontalAlignment(0);
                paragraph.add(t);
                document.add(paragraph);
                document.newPage();
                Paragraph paragraph1 =new Paragraph();
                paragraph1.setFont(f);
                paragraph1.add("              RULES");
                paragraph1.setFont(f1);
                paragraph1.add("\n1.  All Books are issued for 7\n    days.");
                paragraph1.add("\n2.  Only one Book can be\n     borrowed on this ticket.");
                paragraph1.add("\n3.  The holder of this ticket will be\n     responsible for the books");
                paragraph1.add("\n4.  A sum of Rs. 10/- Will be\n     charged for the loss or\n     damage of this ticket.");
                paragraph1.add("\n5.  This ticket must be deposited\n      while leaving the semester.");
                paragraph1.setFont(f2);
                paragraph1.add("\n                               LIBRARIAN");
                paragraph1.setFont(f1);
                document.add(paragraph1);
                document.close();
                dispose();
                new firstpage().setVisible(true);
                Desktop.getDesktop().open(file1);
        }
        catch(DocumentException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        catch(IOException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
        catch(NullPointerException eb)
        {
            JOptionPane.showMessageDialog(null, "Enter All Informationn");
        }
        
    }
}
