package project;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.TabStop;
import com.itextpdf.text.TabStop.Alignment;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.*;
/**
 *
 * @author NODE5
 */
public class icardpage extends JFrame {
        String name1;
        int enrollmentno1;
        String branch1;
        String dateofbirth1;
        String bloodGr1;
        String dateofadmission1;
        String address1;
        String mobileno1;
        String phoneno1;
    /**
     * Creates new form deletepage
     */
    public icardpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        enrollmentno = new javax.swing.JLabel();
        enrollmentnofill = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        back3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mobilenofill = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        phonenofill = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("I Card");

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 0), 4, true));

        enrollmentno.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        enrollmentno.setText("Enrollment No");

        enrollmentnofill.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        enrollmentnofill.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                enrollmentnofillKeyTyped(evt);
            }
        });

        submit.setBackground(new java.awt.Color(204, 204, 204));
        submit.setFont(new java.awt.Font("Times New Roman", 0, 23)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        back3.setBackground(new java.awt.Color(204, 204, 204));
        back3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        back3.setText("Back");
        back3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Mobile No.");

        mobilenofill.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        mobilenofill.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mobilenofillKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Phone No.");

        phonenofill.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        phonenofill.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phonenofillKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel8.setText("Student Information Management System");

        jLabel3.setBackground(new java.awt.Color(255, 153, 0));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Identity Card");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(541, 541, 541)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(390, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(back3)
                        .addGap(114, 114, 114)
                        .addComponent(submit)
                        .addGap(555, 555, 555))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(320, 320, 320))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enrollmentno)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(125, 125, 125)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phonenofill, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mobilenofill, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enrollmentnofill, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addGap(26, 26, 26)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enrollmentno, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enrollmentnofill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mobilenofill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phonenofill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back3)
                    .addComponent(submit))
                .addContainerGap(232, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back3ActionPerformed
        dispose();
        new firstpage().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_back3ActionPerformed

    private void enrollmentnofillKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enrollmentnofillKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)|| (c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE)))
        {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_enrollmentnofillKeyTyped

    private void mobilenofillKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobilenofillKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)|| (c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE)))
        {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_mobilenofillKeyTyped

    private void phonenofillKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phonenofillKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)|| (c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE)))
        {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_phonenofillKeyTyped

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed

        try
        {
            //no1=Nofill.getText();
            enrollmentno1=Integer.parseInt(enrollmentnofill.getText());
            //reason1=reason.getText();
            //dt1=datefill.getDate();
            //year1=yearfill.getText();
            //semester1=semesterfill.getText();
            //reason1=reasonfill.getText();
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            Connection con=DriverManager.getConnection("jdbc:ucanaccess://D:\\project\\project\\project.accdb");
            int i=0;
            String sql="SELECT  Enrollment , Name , DateofBirth , DateofAdmission , GroupofBlood , Course , Address FROM registerpage";
            PreparedStatement p=con.prepareStatement(sql);
            ResultSet r=null;
            r=p.executeQuery();
        while (r.next())
        {
            if(r.getInt(1)==Integer.parseInt(enrollmentnofill.getText()))
            {
                i=1;
                name1=r.getString(2);
                enrollmentno1=r.getInt(1);
                branch1=r.getString(6);
                dateofbirth1=r.getString(3);
                bloodGr1=r.getString(5);
                dateofadmission1=r.getString(4);
                address1=r.getString(7);
                mobileno1=mobilenofill.getText();
                char char1=mobileno1.charAt(0);
                phoneno1=phonenofill.getText();
                char char2=phoneno1.charAt(0);
                //branc1=r.getString();
                //course1=r.getString(3);
            }
            else
            {
                continue;
            }
        }
        if (i==1)
        {
         document1();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "number is not found");
        }
        }
        catch(NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(null, "Fill All Information");
        }
        catch(NullPointerException eb)
        {
            JOptionPane.showMessageDialog(null, "Fill All Information");
        }
        catch(ClassNotFoundException | SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        catch(StringIndexOutOfBoundsException sioobe)
        {
            JOptionPane.showMessageDialog(null, "Fill All Information");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(icardpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(icardpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(icardpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(icardpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new icardpage().setVisible(true);
               
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back3;
    private javax.swing.JLabel enrollmentno;
    private javax.swing.JTextField enrollmentnofill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mobilenofill;
    private javax.swing.JTextField phonenofill;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables

    private void document1() {
        String file="D:\\project\\project\\icarddocument.pdf";
        File file1 = new File(file);
        Document document = new Document();
        Rectangle r=new Rectangle(510,300);
        Font f=new Font();
        f.setStyle(Font.BOLD);
        f.setSize(18);
        f.setFamily(FontFactory.TIMES_ROMAN);
        Font f1=new Font();
        f1.setFamily(FontFactory.TIMES_ROMAN);
        Font f2=new Font();
        f2.setStyle(Font.BOLD);
        f2.setSize(14);
        f2.setFamily(FontFactory.TIMES_ROMAN);
        Font f3=new Font();
        f3.setFamily(FontFactory.TIMES_ROMAN);
        f3.setColor(BaseColor.RED);
        document.setPageSize(r);
         try 
         {
                PdfWriter.getInstance(document,new FileOutputStream(file));
                document.open();
                Paragraph paragraph =new Paragraph();
                
                paragraph.setFont(f);
                paragraph.add("    GOVERNMENT POLYTECHNIC, MURTIZAPUR");
                paragraph.setFont(f1);
                paragraph.add("\n                                  NH-6, Amaravati Road, Murtizapur Dist. Akola");
                paragraph.add("\n                                                    Ph. (07256) 207876, 207877");
                paragraph.setFont(f);
                paragraph.add("___________________________________________");
                PdfPTable t=new PdfPTable(1);
                PdfPCell c=new PdfPCell(new Paragraph("\n\n\n"));
                t.addCell(c);
                t.setWidthPercentage(35);
                t.setHorizontalAlignment(0);
                //paragraph.setAlignment(3);
                paragraph.setFont(f1);
                paragraph.add("\n\n                                                    Name:-"+name1);
                paragraph.add("\n                                                    Enrollment No. :-"+enrollmentno1);
                paragraph.add("\n             Photo                              Branch :-"+branch1);
                paragraph.add("\n                                                    Date Of Birth :- "+dateofbirth1+"    Blood Gr :- "+bloodGr1);
                paragraph.add("\n                                                    Date Of Admission :- "+dateofadmission1);
                paragraph.add("\n\n");
                paragraph.setFont(f2);
                paragraph.add("\nPrinciple                                 H.O.D                         Candidate sign");
                
                paragraph.add("\n\n                                                      RENEWAL");
                paragraph.add("\n");
                //paragraph.add("\n Year                                    Session                                H.O.D");
                paragraph.setFont(f1);
                PdfPTable table1=new PdfPTable(3);
                PdfPCell c1=new PdfPCell(new Paragraph("Year"));
                PdfPCell c2=new PdfPCell(new Paragraph("Session"));
                PdfPCell c3=new PdfPCell(new Paragraph("H.O.D"));
                c1.setHorizontalAlignment(Element.ALIGN_CENTER);
                c2.setHorizontalAlignment(Element.ALIGN_CENTER);
                c3.setHorizontalAlignment(Element.ALIGN_CENTER);
                table1.addCell(c1);
                table1.addCell(c2);
                table1.addCell(c3);
                PdfPCell c4=new PdfPCell(new Paragraph("2"));
                c4.setHorizontalAlignment(Element.ALIGN_CENTER);
                table1.addCell(c4);
                table1.addCell(" ");
                table1.addCell(" ");
                PdfPCell c5=new PdfPCell(new Paragraph("3"));
                c5.setHorizontalAlignment(Element.ALIGN_CENTER);
                table1.addCell(c5);
                table1.addCell(" ");
                table1.addCell(" ");
                paragraph.add(table1);
                //paragraph.add("\n      2                                 ____________________                   _____________");
                //paragraph.add("\n      3                                 ____________________                   _____________");
                paragraph.add("\nAddress  :-  "+address1);
                paragraph.add("\nMobile No.:- "+mobileno1+"  Ph.No."+phoneno1);
                paragraph.add("\n________________________________________________________________");
                paragraph.add("INSTRUCTIONS :- 1) Student must dispaly I-Card using neck string while in institute campus.");
                paragraph.add("2) This I-Card is vaild only for the student named and for the year indicated.");
                paragraph.add("3) This I-Card is non transferable and must be produced whenever demanded .");
                paragraph.add("4) In case of loss of this I-Card, must intimate immediate to the principal in writting.");
                paragraph.setFont(f3);
                paragraph.add("   IF FOUND PLEASE SURRENDER TO THE INSTITUTE.");
                paragraph.setFont(f1);
                document.add(paragraph);
                document.close();
                dispose();
                new firstpage().setVisible(true);
                Desktop.getDesktop().open(file1);
                
         }
         catch(DocumentException | IOException | NullPointerException e)
         {
             JOptionPane.showMessageDialog(null, e);
         }
    }
}
