/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author CO2
 */
public class informationtechnologyrollcalllist extends javax.swing.JFrame {
String rollcallbranch="1";
String department="Information Technology";
String year="2018-2019";
String course="IF-6G";
String selectsemester5;
String[] selectsemester51={"","First", "Second", "Third", "Fourth", "Fifth", "Sixth"};
    /**
     * Creates new form computerrollcalllist
     */
    public informationtechnologyrollcalllist() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        coursesemesterfill1 = new javax.swing.JLabel();
        selectsemester1 = new javax.swing.JComboBox();
        selectscheme1 = new javax.swing.JComboBox();
        submit = new javax.swing.JButton();
        back3 = new javax.swing.JButton();
        selectcourse1 = new javax.swing.JComboBox();
        yearchoose1 = new com.toedter.calendar.JYearChooser();
        yearlabel = new javax.swing.JLabel();
        yearchoose2 = new com.toedter.calendar.JYearChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Information Technology Roll Call List");

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 0), 4, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(1400, 663));
        jPanel1.setRequestFocusEnabled(false);

        coursesemesterfill1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        coursesemesterfill1.setText("Course / Semester");

        selectsemester1.setBackground(new java.awt.Color(255, 255, 102));
        selectsemester1.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        selectsemester1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---Select Semester---", "1", "2", "3", "4", "5", "6" }));

        selectscheme1.setBackground(new java.awt.Color(255, 255, 102));
        selectscheme1.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        selectscheme1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---Select Scheme---", "E", "G", "I" }));

        submit.setBackground(new java.awt.Color(204, 204, 204));
        submit.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        back3.setBackground(new java.awt.Color(204, 204, 204));
        back3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        back3.setText("Back");
        back3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back3ActionPerformed(evt);
            }
        });

        selectcourse1.setBackground(new java.awt.Color(255, 255, 102));
        selectcourse1.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        selectcourse1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "IF" }));
        selectcourse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectcourse1ActionPerformed(evt);
            }
        });

        yearchoose1.setBackground(new java.awt.Color(255, 255, 102));
        yearchoose1.setValue(2018);

        yearlabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        yearlabel.setText("Year");

        yearchoose2.setBackground(new java.awt.Color(255, 255, 102));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel8.setText("Student Information Management System");

        jLabel2.setBackground(new java.awt.Color(255, 153, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Information Technology");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(427, 427, 427)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yearlabel)
                            .addComponent(coursesemesterfill1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(386, 386, 386)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(521, 521, 521)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(719, 719, 719)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(yearchoose1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(yearchoose2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(selectscheme1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectsemester1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectcourse1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(505, 505, 505)
                        .addComponent(back3)
                        .addGap(131, 131, 131)
                        .addComponent(submit)))
                .addContainerGap(318, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel8)
                .addGap(10, 10, 10)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coursesemesterfill1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectcourse1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectsemester1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectscheme1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yearchoose1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearchoose2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(117, 117, 117)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back3)
                    .addComponent(submit))
                .addGap(133, 133, 133))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1349, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        try
        {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            Connection con=DriverManager.getConnection("jdbc:ucanaccess://D:\\project\\project\\project.accdb");
            String a123=(String) selectcourse1.getSelectedItem();
            String a124=(String) selectsemester1.getSelectedItem();
            String a125=(String) selectscheme1.getSelectedItem();
            a123=a123.concat("-");
            a123=a123.concat(a124);
            a123=a123.concat(a125);
            rollcallbranch=a123;
            String y1=Integer.toString(yearchoose1.getYear());
            String y2=Integer.toString(yearchoose2.getYear());
            y1=y1.concat("-");
            y1=y1.concat(y2);
            year=y1;
            documentrollcall();
            dispose();
            new firstpage().setVisible(true);
        }
        catch(ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        catch(NumberFormatException nfe)
        {
            JOptionPane.showMessageDialog(null,"Select All Values");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_submitActionPerformed

    private void back3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back3ActionPerformed
        dispose();
        new firstpage().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_back3ActionPerformed

    private void selectcourse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectcourse1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectcourse1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(informationtechnologyrollcalllist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(informationtechnologyrollcalllist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(informationtechnologyrollcalllist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(informationtechnologyrollcalllist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new informationtechnologyrollcalllist().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back3;
    private javax.swing.JLabel coursesemesterfill1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox selectcourse1;
    private javax.swing.JComboBox selectscheme1;
    private javax.swing.JComboBox selectsemester1;
    private javax.swing.JButton submit;
    private com.toedter.calendar.JYearChooser yearchoose1;
    private com.toedter.calendar.JYearChooser yearchoose2;
    private javax.swing.JLabel yearlabel;
    // End of variables declaration//GEN-END:variables
void documentrollcall()
{
    Document document = new Document();
        int i=1;
        String file="D:\\project\\project\\rollcalllist.pdf";
        Font f=new Font();
        f.setFamily(FontFactory.TIMES_ROMAN);
        f.setSize(18);
        Font f1=new Font();
        f1.setFamily(FontFactory.TIMES_ROMAN);
        File file1 = new File(file);
        try {
            PdfWriter.getInstance(document,new FileOutputStream(file));
        
                document.open();
                Paragraph paragraph =new Paragraph();
                int i23;
        //i23 = new Integer(2);
                String s=selectsemester1.getSelectedItem().toString();
                i23=Integer.parseInt(s);
                selectsemester5=selectsemester51[i23];
                paragraph.setFont(f);
                paragraph.add("                                       Provisional Roll Call List\n\n");
                paragraph.add("                                "+department+" Department\n\n");
                paragraph.add("                            "+selectsemester5+" Semester Acadmic Year "+year+"\n\n");
                paragraph.add("                                               "+rollcallbranch+"\n\n");
                PdfPTable t=new PdfPTable(4);
                t.setWidths(new int[]{1,3,7,2});
                paragraph.setFont(f1);
                PdfPCell c=new PdfPCell(new Paragraph("Roll No."));
                PdfPCell c1=new PdfPCell(new Paragraph("Enrollment No"));
                PdfPCell c2=new PdfPCell(new Paragraph("Name of Student"));
                PdfPCell c3=new PdfPCell(new Paragraph("Remark"));
                //c.setColspan(1);
                c.setHorizontalAlignment(Element.ALIGN_CENTER);
                t.setHeaderRows(3);
                t.addCell(c);
                t.addCell(c1);                
                t.addCell(c2);
                t.addCell(c3);
               Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            Connection con=DriverManager.getConnection("jdbc:ucanaccess://D:\\project\\project\\project.accdb");
            String sql="SELECT Enrollment,Name,coursesemester,DC FROM registerpage";
            PreparedStatement p=con.prepareStatement(sql);
            ResultSet r=null;
            r=p.executeQuery();
            paragraph.setAlignment(3);
            while (r.next())
            {
                if(rollcallbranch.equalsIgnoreCase(r.getString(3))&&(r.getString(4).equalsIgnoreCase("No")))
                {
               t.addCell(Integer.toString(i));
               t.addCell(Integer.toString(r.getInt(1)));
               t.addCell(r.getString(2).toUpperCase());
               t.addCell("  ");
               i++;
                }
        }
           
                document.add(paragraph);
                document.add(t);
                document.close();
                Desktop.getDesktop().open(file1);
        }
        catch(DocumentException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        catch(ClassNotFoundException ea)
        {
            JOptionPane.showMessageDialog(null, ea);
        }
        catch(SQLException eb)
        {
             JOptionPane.showMessageDialog(null, eb);
        }
        catch(IOException ec)
        {
            JOptionPane.showMessageDialog(null, ec);
        }
         
    }
}

