package project;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.util.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.*;
import project.DateToWords;
import java.lang.NullPointerException;
import java.sql.SQLException;
import java.text.Format;
import java.text.SimpleDateFormat;
/**
 *
 * @author NODE5
 */
public class registerpage extends JFrame {
            String  MobileNo ; 
            int        Enrollment;
            Date DateofBirth1=new Date();
            Date DateofAdmission1=new Date();;
            //Date DateofBirthinWord=new Date();
            DateToWords dw=new DateToWords();
            String Name , Cast , NameofMother , Nationality , Gender , PlaceofBirth , Institutionlastattended , DateofBirthinWord , GroupofBlood , Course , Registerno , Address;
            String coursesemester,DC;
            /**
     * Creates new form deletepage
     */
    public registerpage() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderbutton = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        caste = new javax.swing.JLabel();
        castefill = new javax.swing.JTextField();
        nameofmother = new javax.swing.JLabel();
        nameofmotherfill = new javax.swing.JTextField();
        nationality = new javax.swing.JLabel();
        nationalityfill = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        enrollmentno = new javax.swing.JLabel();
        enrollmentnofill = new javax.swing.JTextField();
        dateofbirth = new javax.swing.JLabel();
        dateofadmission = new javax.swing.JLabel();
        birthofdatefill = new com.toedter.calendar.JDateChooser();
        dateofadmition = new com.toedter.calendar.JDateChooser();
        gender = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        other = new javax.swing.JRadioButton();
        placeofbirth = new javax.swing.JLabel();
        placeofbirthfill = new javax.swing.JTextField();
        institutionlastattende = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        Submit = new javax.swing.JButton();
        dateofbirthinword = new javax.swing.JLabel();
        dateofbirthinwordfill = new javax.swing.JTextField();
        namefill = new javax.swing.JTextField();
        branch = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        registernumberfill = new javax.swing.JTextField();
        bloodgr = new javax.swing.JLabel();
        mobileno = new javax.swing.JLabel();
        mobilefill = new javax.swing.JTextField();
        filldateofbirth = new javax.swing.JButton();
        address = new javax.swing.JLabel();
        branchfill = new javax.swing.JComboBox();
        bloodgrfill = new javax.swing.JComboBox();
        coursesemesterfill = new javax.swing.JLabel();
        selectscheme = new javax.swing.JComboBox();
        selectsemester = new javax.swing.JComboBox();
        selectcourse = new javax.swing.JComboBox();
        fillregisternumberbutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        addressfill = new javax.swing.JTextField();
        institutionlastattendedfill = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Registration");
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 0), 4, true));
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 3));

        caste.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        caste.setText("Caste");

        castefill.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        castefill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                castefillActionPerformed(evt);
            }
        });

        nameofmother.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nameofmother.setText("Name Of Mother");

        nameofmotherfill.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        nameofmotherfill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameofmotherfillActionPerformed(evt);
            }
        });

        nationality.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nationality.setText("Nationality");

        nationalityfill.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        nationalityfill.setText("Indian");

        name.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        name.setText("Name");

        enrollmentno.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        enrollmentno.setText("Enrollment No.");

        enrollmentnofill.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        enrollmentnofill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollmentnofillActionPerformed(evt);
            }
        });
        enrollmentnofill.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                enrollmentnofillKeyTyped(evt);
            }
        });

        dateofbirth.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        dateofbirth.setText("Date Of Birth");

        dateofadmission.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        dateofadmission.setText("Date of Admission");

        birthofdatefill.setBackground(new java.awt.Color(255, 255, 102));
        birthofdatefill.setDateFormatString("dd/MM/yyyy");
        birthofdatefill.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N

        dateofadmition.setBackground(new java.awt.Color(255, 255, 102));
        dateofadmition.setDateFormatString("dd/MM/yyyy");
        dateofadmition.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N

        gender.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        gender.setText("Gender");

        male.setBackground(new java.awt.Color(255, 255, 102));
        genderbutton.add(male);
        male.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        male.setText("Male");

        female.setBackground(new java.awt.Color(255, 255, 102));
        genderbutton.add(female);
        female.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        female.setText("Female");

        other.setBackground(new java.awt.Color(255, 255, 102));
        genderbutton.add(other);
        other.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        other.setText("Other");

        placeofbirth.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        placeofbirth.setText("Place of Birth");

        placeofbirthfill.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        placeofbirthfill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeofbirthfillActionPerformed(evt);
            }
        });

        institutionlastattende.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        institutionlastattende.setText("Institution last attended");

        back.setBackground(new java.awt.Color(204, 204, 204));
        back.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        Submit.setBackground(new java.awt.Color(204, 204, 204));
        Submit.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        dateofbirthinword.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        dateofbirthinword.setText("Date Of Birth In Word");

        dateofbirthinwordfill.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N

        namefill.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        namefill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namefillActionPerformed(evt);
            }
        });

        branch.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        branch.setText("Branch");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Register Number");

        registernumberfill.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        registernumberfill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registernumberfillActionPerformed(evt);
            }
        });

        bloodgr.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bloodgr.setText("Blood Gr.");

        mobileno.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        mobileno.setText("Mobile No");

        mobilefill.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        mobilefill.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mobilefillKeyTyped(evt);
            }
        });

        filldateofbirth.setBackground(new java.awt.Color(204, 204, 204));
        filldateofbirth.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        filldateofbirth.setText("Fill Date Of Birth");
        filldateofbirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filldateofbirthActionPerformed(evt);
            }
        });

        address.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        address.setText("Address");

        branchfill.setBackground(new java.awt.Color(255, 255, 102));
        branchfill.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        branchfill.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----Select Branch----", "Computer Engineering", "Electrical Engineering", "Mechanical Engineering", "Information Technology" }));

        bloodgrfill.setBackground(new java.awt.Color(255, 255, 102));
        bloodgrfill.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        bloodgrfill.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---Select Blood Group--", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));

        coursesemesterfill.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        coursesemesterfill.setText("Course / Semester");

        selectscheme.setBackground(new java.awt.Color(255, 255, 102));
        selectscheme.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        selectscheme.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---Select Scheme---", "E", "G", "I" }));
        selectscheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectschemeActionPerformed(evt);
            }
        });

        selectsemester.setBackground(new java.awt.Color(255, 255, 102));
        selectsemester.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        selectsemester.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---Select Semester---", "1", "2", "3", "4", "5", "6" }));

        selectcourse.setBackground(new java.awt.Color(255, 255, 102));
        selectcourse.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        selectcourse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---Select Course---", "CO", "EE", "ME", "IF" }));
        selectcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectcourseActionPerformed(evt);
            }
        });

        fillregisternumberbutton.setBackground(new java.awt.Color(204, 204, 204));
        fillregisternumberbutton.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        fillregisternumberbutton.setText("Fill Register Number");
        fillregisternumberbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillregisternumberbuttonActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 153, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Student Registration");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel8.setText("Student Information Management System");

        institutionlastattendedfill.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        institutionlastattendedfill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                institutionlastattendedfillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(521, 521, 521)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(back)
                        .addGap(100, 100, 100)
                        .addComponent(Submit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nationality)
                    .addComponent(dateofadmission)
                    .addComponent(institutionlastattende)
                    .addComponent(dateofbirthinword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(placeofbirth)
                    .addComponent(jLabel1)
                    .addComponent(bloodgr)
                    .addComponent(mobileno)
                    .addComponent(branch)
                    .addComponent(name)
                    .addComponent(caste, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameofmother, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateofbirth, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enrollmentno))
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nationalityfill, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateofadmition, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namefill, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(castefill, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(institutionlastattendedfill, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mobilefill, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(placeofbirthfill, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enrollmentnofill, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(birthofdatefill, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateofbirthinwordfill, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(registernumberfill, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bloodgrfill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fillregisternumberbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(filldateofbirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(male)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(female)
                                .addGap(2, 2, 2)
                                .addComponent(other))
                            .addComponent(branchfill, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameofmotherfill, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addressfill, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(coursesemesterfill)
                                .addGap(28, 28, 28)
                                .addComponent(selectcourse, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selectscheme, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(selectsemester, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(55, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel8)
                .addGap(6, 6, 6)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namefill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressfill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selectcourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coursesemesterfill))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectsemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectscheme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enrollmentnofill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enrollmentno, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(birthofdatefill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateofbirth, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(castefill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caste, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameofmother, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameofmotherfill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nationalityfill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nationality, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dateofadmition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(male)
                            .addComponent(other)
                            .addComponent(female)
                            .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(dateofadmission, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(placeofbirthfill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(placeofbirth, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(institutionlastattende, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(institutionlastattendedfill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dateofbirthinwordfill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(filldateofbirth))
                    .addComponent(dateofbirthinword, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(branch, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(branchfill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(registernumberfill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fillregisternumberbutton)))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bloodgr, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bloodgrfill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobilefill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mobileno, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(Submit))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mobilefillKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobilefillKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)|| (c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_mobilefillKeyTyped

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        try
        {

            male.setActionCommand("Male");
            female.setActionCommand("Female");
            other.setActionCommand("Other");
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            Connection con=DriverManager.getConnection("jdbc:ucanaccess://D:\\project\\project\\project.accdb");
            int i=0;
            String sql="SELECT Enrollment FROM registerpage";
            PreparedStatement p=con.prepareStatement(sql);
            ResultSet r=null;
            r=p.executeQuery();
            while (r.next())
            {
                if(r.getInt(1)!=Integer.parseInt(enrollmentnofill.getText()))
                {
                    continue;
                }
                else
                {
                    i=2;
                    break;
                }
            }
            if (i==0)
            {
                Enrollment=Integer.parseInt(enrollmentnofill.getText());
                Name=namefill.getText();
                DateofBirth1=birthofdatefill.getDate();
                //String s123=birthofdatefill.getDate();
                SimpleDateFormat f=new SimpleDateFormat("dd/MM/yyyy");
                //System.out.println(DateofBirth);
                String DateofBirth=f.format(DateofBirth1);
                Cast=castefill.getText();
                NameofMother=nameofmotherfill.getText();
                Nationality=nationalityfill.getText();
                DateofAdmission1=dateofadmition.getDate();
                SimpleDateFormat f1=new SimpleDateFormat("dd/MM/yyyy");
                //System.out.println(DateofBirth);
                String DateofAdmission=f1.format(DateofAdmission1);
                Gender=genderbutton.getSelection().getActionCommand();
                PlaceofBirth=placeofbirthfill.getText();
                Institutionlastattended=institutionlastattendedfill.getText();
                //String s1=dw.setDateInWords(DateofBirth);

                DateofBirthinWord=dateofbirthinwordfill.getText();
                
                GroupofBlood=(String) bloodgrfill.getSelectedItem();
                MobileNo=mobilefill.getText();
                //Course=branchfill.getSelectedIndex();
                Course=(String) branchfill.getSelectedItem();
                Registerno=registernumberfill.getText();
                Address=addressfill.getText();
                String a123=(String) selectcourse.getSelectedItem();
                String a124=(String) selectsemester.getSelectedItem();
                String a125=(String) selectscheme.getSelectedItem();
                a123=a123.concat("-");
                a123=a123.concat(a124);
                a123=a123.concat(a125);
                coursesemester=a123;
                DC="No";
                /*p1.setLong(1,Enrollment);
                p1.setString(2,Name);
                p1.setDate(3, new java.sql.Date(DateofBirth.getDate()));
                p1.setString(4, Cast);
                p1.setString(5, NameofMother);
                p1.setString(6, Nationality);
                p1.setDate(7, new java.sql.Date(DateofAdmission.getDate()));
                p1.setString(8, Gender);
                p1.setString(9, PlaceofBirth);
                p1.setString(10, Institutionlastattended);
                p1.setString(11, DateofBirthinWord);
                p1.setString(12, GroupofBlood);
                p1.setLong(13, MobileNo);
                p1.setString(14, Course);
                p1.setString(15, Registerno);
                p1.setString(16, Address);*/
                String sql1="insert into registerpage (Enrollment , Name , DateofBirth , Cast , NameofMother , Nationality , DateofAdmission , Gender , PlaceofBirth , Institutionlastattended , DateofBirthinWord , GroupofBlood  , MobileNo , Course , Registerno , Address,coursesemester,DC) values('"+Enrollment+"','"+Name+"','"+DateofBirth+"','"+Cast+"','"+NameofMother+"','"+Nationality+"','"+DateofAdmission+"','"+Gender+"','"+PlaceofBirth+"','"+Institutionlastattended+"','"+DateofBirthinWord+"','"+GroupofBlood+"','"+MobileNo+"','"+Course+"','"+Registerno+"','"+Address+"','"+coursesemester+"','"+DC+"')";
                PreparedStatement p1=con.prepareStatement(sql1);
                p1.executeUpdate();
                JOptionPane.showMessageDialog(null, "Student is Successful Register");
                                dispose();
                new firstpage().setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Student is already Register");
            }
        }
        catch(ClassNotFoundException | SQLException | HeadlessException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        catch(NumberFormatException nfe)
        {
            JOptionPane.showMessageDialog(null, "Fill All Informations");
        }
        catch(NullPointerException npe1)
        {
            JOptionPane.showMessageDialog(null, "Fill All Informations");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
                        dispose();
        new firstpage().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void enrollmentnofillKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enrollmentnofillKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)|| (c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE)))
        {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_enrollmentnofillKeyTyped

    private void nameofmotherfillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameofmotherfillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameofmotherfillActionPerformed

    private void castefillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_castefillActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_castefillActionPerformed

    private void filldateofbirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filldateofbirthActionPerformed
        DateofBirth1=birthofdatefill.getDate();
        String s1=dw.setDateInWords(DateofBirth1);
        dateofbirthinwordfill.setText(s1);
        // TODO add your handling code here
    }//GEN-LAST:event_filldateofbirthActionPerformed

    private void namefillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namefillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namefillActionPerformed

    private void fillregisternumberbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillregisternumberbuttonActionPerformed
        try
        {
        String erno1;
        erno1=enrollmentnofill.getText();
        char ern1=erno1.charAt(0);
        
        char ern2=erno1.charAt(1);
        //JOptionPane.showMessageDialog(null,ern2);
        //int numberern=10;
        int numberern=ern1;
        int numberern1=ern2;
        numberern=numberern-48;
        numberern1=numberern1-48;
        //JOptionPane.showMessageDialog(null,numberern1);
        //String numberern1string="1";
        numberern=numberern*10;
        numberern=numberern+numberern1;
        int numberern2=numberern+1;
        String numberernstring=Integer.toString(numberern);
        numberernstring=numberernstring.concat("-");
        String numberernstring1=Integer.toString(numberern2);
        numberernstring=numberernstring.concat(numberernstring1);
        numberernstring=numberernstring.concat("/");
        //String register1234;
        String collegenameern="GPMZR/";
        String branchern="1";
        /*
         * ----Select Branch----, Computer Engineering, Electrical Engineering, Mechanical Engineering, Information Technology
         * ---SELECT COURSE---, CO, EE, ME, IF
         */
        if(branchfill.getSelectedIndex()==1)
        {
            selectcourse.setSelectedIndex(1);
            branchern="CO/";
        }
        if(branchfill.getSelectedIndex()==2)
        {
            selectcourse.setSelectedIndex(2);
            branchern="EE/";
        }
        if(branchfill.getSelectedIndex()==3)
        {
            selectcourse.setSelectedIndex(3);
            branchern="ME";
        }
        if(branchfill.getSelectedIndex()==4)
        {
            selectcourse.setSelectedIndex(4);
            branchern="IF";
        }
        collegenameern=collegenameern.concat(branchern);
        collegenameern=collegenameern.concat(numberernstring);
        collegenameern=collegenameern.concat(erno1);
        registernumberfill.setText(collegenameern);
        //String branchern= (String) branchfill.getSelectedItem();
        //=Integer.toString(numberern);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_fillregisternumberbuttonActionPerformed

    private void enrollmentnofillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollmentnofillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enrollmentnofillActionPerformed

    private void selectcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectcourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectcourseActionPerformed

    private void placeofbirthfillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeofbirthfillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placeofbirthfillActionPerformed

    private void institutionlastattendedfillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_institutionlastattendedfillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_institutionlastattendedfillActionPerformed

    private void registernumberfillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registernumberfillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registernumberfillActionPerformed

    private void selectschemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectschemeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectschemeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerpage().setVisible(true);
               
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Submit;
    private javax.swing.JLabel address;
    private javax.swing.JTextField addressfill;
    private javax.swing.JButton back;
    private com.toedter.calendar.JDateChooser birthofdatefill;
    private javax.swing.JLabel bloodgr;
    private javax.swing.JComboBox bloodgrfill;
    private javax.swing.JLabel branch;
    private javax.swing.JComboBox branchfill;
    private javax.swing.JLabel caste;
    private javax.swing.JTextField castefill;
    private javax.swing.JLabel coursesemesterfill;
    private javax.swing.JLabel dateofadmission;
    private com.toedter.calendar.JDateChooser dateofadmition;
    private javax.swing.JLabel dateofbirth;
    private javax.swing.JLabel dateofbirthinword;
    private javax.swing.JTextField dateofbirthinwordfill;
    private javax.swing.JLabel enrollmentno;
    private javax.swing.JTextField enrollmentnofill;
    private javax.swing.JRadioButton female;
    private javax.swing.JButton filldateofbirth;
    private javax.swing.JButton fillregisternumberbutton;
    private javax.swing.JLabel gender;
    private javax.swing.ButtonGroup genderbutton;
    private javax.swing.JLabel institutionlastattende;
    private javax.swing.JTextField institutionlastattendedfill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField mobilefill;
    private javax.swing.JLabel mobileno;
    private javax.swing.JLabel name;
    private javax.swing.JTextField namefill;
    private javax.swing.JLabel nameofmother;
    private javax.swing.JTextField nameofmotherfill;
    private javax.swing.JLabel nationality;
    private javax.swing.JTextField nationalityfill;
    private javax.swing.JRadioButton other;
    private javax.swing.JLabel placeofbirth;
    private javax.swing.JTextField placeofbirthfill;
    private javax.swing.JTextField registernumberfill;
    private javax.swing.JComboBox selectcourse;
    private javax.swing.JComboBox selectscheme;
    private javax.swing.JComboBox selectsemester;
    // End of variables declaration//GEN-END:variables
}

